Controllers/NotesController/EditNoteController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using ToDoListWebApp.Context;
using ToDoListWebApp.Models;
using ToDoListWebApp.ViewModels.Notes;

namespace ToDoListWebApp.Controllers.NotesController
{
    public class EditNoteController : Controller
    {
        private readonly ToDoListContext _context;

        public EditNoteController(ToDoListContext context)
        {
            _context = context;
        }
        // GET
        public async Task<IActionResult> EditNote(string idNote)
        {
            var note = await _context.Notes.FindAsync(new Guid(idNote));
            var model = new EditNoteViewModel()
            {
                Id = note.Id,
                Header = note.Header,
                Text = note.Text,
                DateCreated = note.DateCreated,
                DateLastChanged = note.DateLastChanged,
                IdUser = note.IdUser
            };
            return View(model);
        }
        [Route("EditNote/SaveChangesAsync")]
        public async Task<IActionResult> SaveChangesAsync(EditNoteViewModel editNoteViewModel)
        {
	        var note = await _context.Notes.FindAsync(editNoteViewModel.Id);
	        note.Header = editNoteViewModel.Header;
	        note.Text = editNoteViewModel.Text;
            note.DateLastChanged = DateTime.Now;

	        try
            {
	            _context.Entry(note).State = EntityState.Modified;
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NoteExists(editNoteViewModel.Id))
                {
                    return RedirectToAction("Index", "Index");
                }

                throw;
            }
            
            return RedirectToAction("Index", "Index");
        }
        
        private bool NoteExists(Guid id)
        {
            return _context.Notes.Any(e => e.Id == id);
        }
    }
}

Controllers/NotesController/EditReminderController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoListWebApp.Context;
using ToDoListWebApp.ViewModels.Reminders;

namespace ToDoListWebApp.Controllers.NotesController
{
    public class EditReminderController : Controller
    {
        private readonly ToDoListContext _context;

        public EditReminderController(ToDoListContext context)
        {
            _context = context;
        }

        // GET
        public async Task<IActionResult> EditReminder(string idRem)
        {
            var note = await _context.Reminders.FindAsync(new Guid(idRem));
            var model = new ReminderViewModel()
            {
                Id = note.Id,
                Header = note.Header,
                Text = note.Text,
                DateCreated = note.DateCreated,
                DateLastChanged = note.DateLastChanged,
                ReminderDate = note.ReminderDate,
                StatusNote = note.StatusNote,
                IdUser = note.IdUser
            };
            return View(model);
        }

        [Route("EditNote/SaveChangesReminderAsync")]
        public async Task<IActionResult> SaveChangesReminderAsync(ReminderViewModel reminderViewModel)
        {
            var note = await _context.Reminders.FindAsync(reminderViewModel.Id);
            note.Header = reminderViewModel.Header;
            note.Text = reminderViewModel.Text;
            note.DateLastChanged = DateTime.Now;
            note.ReminderDate = new DateTime(reminderViewModel.ReminderDate.Ticks);
            note.StatusNote = reminderViewModel.StatusNote;

            try
            {
                _context.Entry(note).State = EntityState.Modified;
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ReminderExists(reminderViewModel.Id))
                {
                    return RedirectToAction("Index", "Index");
                }

                throw;
            }
            
            return RedirectToAction("Index", "Index");
        }
        
        private bool ReminderExists(Guid id)
        {
            return _context.Reminders.Any(e => e.Id == id);
        }
    }
}

Views/EditReminder/EditReminder.cshtml
@model ToDoListWebApp.ViewModels.Reminders.ReminderViewModel
@{
}
<h1>Редактировать напоминание</h1>

<div class="container">
    <div class="row d-flex justify-content-center align-items-center" style="height: 80vh">
        <div class="col-4 ">
            <form method="post" asp-controller="EditReminder" asp-action="SaveChangesReminder">
                <div class="card md-3" style="border-color: black">
                    <div class="form-col mx-3">
                        <div class="form-group">
                            <label asp-for="Id" hidden>Id</label>
                            <input type="text" class="form-control" asp-for="Id" hidden/>
                        </div>
                        <div class="form-group">
                            <label asp-for="Header">Заголовок</label>
                            <input type="text" class="form-control" asp-for="Header"/>
                        </div>
                        <div class="form-group">
                            <label asp-for="Text">Текст</label>
                            <textarea type="text" class="form-control" asp-for="Text"></textarea>
                        </div>
                        <div class="form-group">
                            <label asp-for="ReminderDate">Дата напомнинания</label>
                            <input asp-for="ReminderDate" type="datetime-local" class="form-control"/>
                        </div>
                        <div>
                            <label asp-for="StatusNote">Статус</label>
                            <select asp-for="StatusNote" required>
                                <option value="0">Complete</option>
                                <option value="1">Failed</option>
                                <option value="2">Low</option>
                                <option value="3">Medium</option>
                                <option value="4">High</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label asp-for="DateCreated">Дата создания</label>
                            <input type="datetime-local" class="form-control" asp-for="DateCreated" disabled="disabled"/>
                        </div>
                        <div class="form-group">
                            <label asp-for="DateLastChanged">Дата последнего изменения</label>
                            <input type="datetime-local" class="form-control" asp-for="DateLastChanged" disabled="disabled"/>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary " asp-controller="EditNote" asp-action="SaveChangesReminderAsync" value="Сохранить"/>
                            <a type="button" class="btn btn-primary center-button" asp-controller="Index" asp-action="Index">Отмена</a> 
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>